version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:8"
    steps:
      - "checkout"
      -
        restore_cache:
          key: "yarn-{{ .Branch }}-{{ checksum \"yarn.lock\" }}"
      - run: "yarn install"
      - run: "yarn lint"
      -
        save_cache:
          key: "yarn-{{ .Branch }}-{{ checksum \"yarn.lock\" }}"
          paths:
            - "~/.yarn-cache"
